# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ee9ef550f91aa79367b56fa74c79a7111d66d24da18a3f2089a08b0c7ab4040469146ce09736ed3303a1be5a1735441a0bb5bf5880f54f910a0815f6bac4a2

test:
  secret_key_base: 10f0cf960d79afdbf46905468f9e3ea9674d5840c23a902374ef3a7498be86992c89747ed2a24f845a64be09d0b960ed4e2686dbe2b2f7123425d2db993d4321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 10f0cf960d79afdbf46905468f9e3ea9674d5840c23a902374ef3a7498be86992c89747ed2a24f845a64be09d0b960ed4e2686dbe2b2f7123425d2db993d4321
